version: 0.2

phases:
  build:
    commands:
      - echo Stepping to build phase.....
      - mvn clean package
    post_build:
      commands:
        - echo Build completed successfully
artifacts:
  files:
    - target/config-service.jar
  discard-paths: yes