

spring:
  application:
    name: client-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KumarRupak/config-server
          clone-on-start: true

